name: Java Maven Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # 1. Checkout
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Java setup
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # 3. Cache dependencies
    - name: Cache Maven Packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2

    # 4. Build using Maven
    - name: Build with Maven
      run: mvn -B clean install

    # 5. Run tests
    - name: Run Maven tests
      run: mvn test

    # 6. Upload JAR file
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: built-jar
        path: target/*.jar
